workflowVersion: 1.0.0
speakeasyVersion: 1.761.4
sources:
    Paygentic API:
        inputs:
            - location: .speakeasy/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/paygentic/default/paygentic-api
targets:
    python:
        target: python
        source: Paygentic API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/paygentic/default/paygentic-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
        testing:
            enabled: true
