"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
import pydantic
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import Annotated, NotRequired, TypedDict


ApprovalObject = Literal["approval",]


ApprovalDecision = Union[
    Literal[
        "pending",
        "approved",
        "rejected",
        "cancelled",
    ],
    UnrecognizedStr,
]


class ApprovalTypedDict(TypedDict):
    id: str
    object: ApprovalObject
    merchant_id: str
    resource_type: str
    resource_id: str
    kind: str
    decision: ApprovalDecision
    requester: str
    data_snapshot_hash: str
    created_at: datetime
    reviewer: NotRequired[Nullable[str]]
    note: NotRequired[Nullable[str]]
    decided_at: NotRequired[Nullable[datetime]]


class Approval(BaseModel):
    id: str

    object: ApprovalObject

    merchant_id: Annotated[str, pydantic.Field(alias="merchantId")]

    resource_type: Annotated[str, pydantic.Field(alias="resourceType")]

    resource_id: Annotated[str, pydantic.Field(alias="resourceId")]

    kind: str

    decision: ApprovalDecision

    requester: str

    data_snapshot_hash: Annotated[str, pydantic.Field(alias="dataSnapshotHash")]

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    reviewer: OptionalNullable[str] = UNSET

    note: OptionalNullable[str] = UNSET

    decided_at: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="decidedAt")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reviewer", "note", "decidedAt"])
        nullable_fields = set(["reviewer", "note", "decidedAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Approval.model_rebuild()
except NameError:
    pass
