"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from paygentic_sdk.types import BaseModel
import pydantic
from typing import Dict
from typing_extensions import Annotated, TypedDict


class CostReportTimeSeriesTypedDict(TypedDict):
    window_start: datetime
    window_end: datetime
    groups: Dict[str, float]
    r"""Map of group key → cost value for this time window. Keys match CostReportGroup.key."""


class CostReportTimeSeries(BaseModel):
    window_start: Annotated[datetime, pydantic.Field(alias="windowStart")]

    window_end: Annotated[datetime, pydantic.Field(alias="windowEnd")]

    groups: Dict[str, float]
    r"""Map of group key → cost value for this time window. Keys match CostReportGroup.key."""


try:
    CostReportTimeSeries.model_rebuild()
except NameError:
    pass
