"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .costreportgroup import CostReportGroup, CostReportGroupTypedDict
from .costreporttimeseries import CostReportTimeSeries, CostReportTimeSeriesTypedDict
from datetime import datetime
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


CostReportResponseObject = Literal["cost_report",]


class PeriodTypedDict(TypedDict):
    from_: datetime
    to: datetime


class Period(BaseModel):
    from_: Annotated[datetime, pydantic.Field(alias="from")]

    to: datetime


class PaginationTypedDict(TypedDict):
    total: int
    limit: int
    offset: int


class Pagination(BaseModel):
    total: int

    limit: int

    offset: int


class CostReportResponseCostRangeTypedDict(TypedDict):
    r"""Where the caller's cost data actually lies in time. Present only when the selected range returned no cost. An object carries the bounds of the real cost events; null means the caller has no cost event at any time; an absent field means the extent was not resolved, because the result was not empty, because the lookup failed, or because the metering service does not serve the bounds method. An absent field must never be read as an absence."""

    from_: datetime
    r"""Earliest cost event instant."""
    to: datetime
    r"""Latest cost event instant."""


class CostReportResponseCostRange(BaseModel):
    r"""Where the caller's cost data actually lies in time. Present only when the selected range returned no cost. An object carries the bounds of the real cost events; null means the caller has no cost event at any time; an absent field means the extent was not resolved, because the result was not empty, because the lookup failed, or because the metering service does not serve the bounds method. An absent field must never be read as an absence."""

    from_: Annotated[datetime, pydantic.Field(alias="from")]
    r"""Earliest cost event instant."""

    to: datetime
    r"""Latest cost event instant."""


class CostReportResponseTypedDict(TypedDict):
    currency: str
    r"""ISO 4217 currency code for all monetary values in this response."""
    period: PeriodTypedDict
    group_by: str
    r"""The active grouping dimension (e.g. 'cost', 'customer', or a dynamic dimension key)."""
    total_cost: float
    r"""Sum of cost across all groups (not just top N)."""
    total_quantity: float
    r"""Sum of quantity across all groups."""
    groups: List[CostReportGroupTypedDict]
    r"""Top N groups plus an 'Other' bucket aggregating the remainder."""
    time_series: List[CostReportTimeSeriesTypedDict]
    r"""Time-bucketed breakdown per group. Keys in each window's 'groups' object correspond to CostReportGroup.key. The 'Other' bucket key is '__other__'."""
    available_dimensions: List[str]
    r"""Dimension keys available for further drill-down (populated when a single cost is filtered)."""
    pagination: PaginationTypedDict
    object: NotRequired[CostReportResponseObject]
    warnings: NotRequired[List[str]]
    r"""Non-fatal warnings, e.g. costs that could not be queried."""
    cost_range: NotRequired[Nullable[CostReportResponseCostRangeTypedDict]]
    r"""Where the caller's cost data actually lies in time. Present only when the selected range returned no cost. An object carries the bounds of the real cost events; null means the caller has no cost event at any time; an absent field means the extent was not resolved, because the result was not empty, because the lookup failed, or because the metering service does not serve the bounds method. An absent field must never be read as an absence."""


class CostReportResponse(BaseModel):
    currency: str
    r"""ISO 4217 currency code for all monetary values in this response."""

    period: Period

    group_by: Annotated[str, pydantic.Field(alias="groupBy")]
    r"""The active grouping dimension (e.g. 'cost', 'customer', or a dynamic dimension key)."""

    total_cost: Annotated[float, pydantic.Field(alias="totalCost")]
    r"""Sum of cost across all groups (not just top N)."""

    total_quantity: Annotated[float, pydantic.Field(alias="totalQuantity")]
    r"""Sum of quantity across all groups."""

    groups: List[CostReportGroup]
    r"""Top N groups plus an 'Other' bucket aggregating the remainder."""

    time_series: Annotated[
        List[CostReportTimeSeries], pydantic.Field(alias="timeSeries")
    ]
    r"""Time-bucketed breakdown per group. Keys in each window's 'groups' object correspond to CostReportGroup.key. The 'Other' bucket key is '__other__'."""

    available_dimensions: Annotated[
        List[str], pydantic.Field(alias="availableDimensions")
    ]
    r"""Dimension keys available for further drill-down (populated when a single cost is filtered)."""

    pagination: Pagination

    object: Optional[CostReportResponseObject] = "cost_report"

    warnings: Optional[List[str]] = None
    r"""Non-fatal warnings, e.g. costs that could not be queried."""

    cost_range: Annotated[
        OptionalNullable[CostReportResponseCostRange], pydantic.Field(alias="costRange")
    ] = UNSET
    r"""Where the caller's cost data actually lies in time. Present only when the selected range returned no cost. An object carries the bounds of the real cost events; null means the caller has no cost event at any time; an absent field means the extent was not resolved, because the result was not empty, because the lookup failed, or because the metering service does not serve the bounds method. An absent field must never be read as an absence."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object", "warnings", "costRange"])
        nullable_fields = set(["costRange"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Period.model_rebuild()
except NameError:
    pass
try:
    CostReportResponseCostRange.model_rebuild()
except NameError:
    pass
try:
    CostReportResponse.model_rebuild()
except NameError:
    pass
