"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class PriorPeriodTypedDict(TypedDict):
    r"""Prior-period comparison data. Present only when comparePriorPeriod=true."""

    cost: float
    change_percent: Nullable[float]
    r"""Percentage change vs prior period. Null when prior period cost is 0."""


class PriorPeriod(BaseModel):
    r"""Prior-period comparison data. Present only when comparePriorPeriod=true."""

    cost: float

    change_percent: Annotated[Nullable[float], pydantic.Field(alias="changePercent")]
    r"""Percentage change vs prior period. Null when prior period cost is 0."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class CostReportGroupTypedDict(TypedDict):
    key: str
    r"""Group identifier (cost ID, customer ID, or dimension value). '__other__' for the aggregated remainder bucket."""
    label: str
    r"""Human-readable display name for the group."""
    total_cost: float
    total_quantity: float
    percent_of_total: float
    r"""This group's share of total cost, 0–100."""
    is_other: bool
    r"""True for the aggregated 'Other' bucket."""
    unit: NotRequired[Nullable[str]]
    r"""Unit label for the quantity (e.g. 'token', 'request')."""
    prior_period: NotRequired[Nullable[PriorPeriodTypedDict]]
    r"""Prior-period comparison data. Present only when comparePriorPeriod=true."""


class CostReportGroup(BaseModel):
    key: str
    r"""Group identifier (cost ID, customer ID, or dimension value). '__other__' for the aggregated remainder bucket."""

    label: str
    r"""Human-readable display name for the group."""

    total_cost: Annotated[float, pydantic.Field(alias="totalCost")]

    total_quantity: Annotated[float, pydantic.Field(alias="totalQuantity")]

    percent_of_total: Annotated[float, pydantic.Field(alias="percentOfTotal")]
    r"""This group's share of total cost, 0–100."""

    is_other: Annotated[bool, pydantic.Field(alias="isOther")]
    r"""True for the aggregated 'Other' bucket."""

    unit: OptionalNullable[str] = UNSET
    r"""Unit label for the quantity (e.g. 'token', 'request')."""

    prior_period: Annotated[
        OptionalNullable[PriorPeriod], pydantic.Field(alias="priorPeriod")
    ] = UNSET
    r"""Prior-period comparison data. Present only when comparePriorPeriod=true."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["unit", "priorPeriod"])
        nullable_fields = set(["unit", "priorPeriod"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PriorPeriod.model_rebuild()
except NameError:
    pass
try:
    CostReportGroup.model_rebuild()
except NameError:
    pass
