"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createpercentagediscountadjustment import (
    CreatePercentageDiscountAdjustment,
    CreatePercentageDiscountAdjustmentTypedDict,
)
from .createusagediscountadjustment import (
    CreateUsageDiscountAdjustment,
    CreateUsageDiscountAdjustmentTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType


CreateSubscriptionAdjustmentRequestTypedDict = TypeAliasType(
    "CreateSubscriptionAdjustmentRequestTypedDict",
    Union[
        CreatePercentageDiscountAdjustmentTypedDict,
        CreateUsageDiscountAdjustmentTypedDict,
    ],
)
r"""One adjustment to attach to the subscription. The type decides which number the body carries: a rate for percentageDiscount, a unit count and one target price for usageDiscount."""


CreateSubscriptionAdjustmentRequest = Annotated[
    Union[CreatePercentageDiscountAdjustment, CreateUsageDiscountAdjustment],
    Field(discriminator="type"),
]
r"""One adjustment to attach to the subscription. The type decides which number the body carries: a rate for percentageDiscount, a unit count and one target price for usageDiscount."""
