"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


CreatePlanTaxBehavior = Literal[
    "exclusive",
    "inclusive",
]
r"""Whether tax is added on top of the price (exclusive) or included in the price (inclusive)"""


BillingVersion = Literal[
    0,
    1,
]
r"""Billing engine version. 0 = legacy fee-schedule billing (Legacy), 1 = line-item billing with metered usage support (Standard)."""


class CreatePlanRequestTypedDict(TypedDict):
    currency: str
    r"""Three-letter ISO 4217 currency code for plan pricing. Must be one of the merchant's supported currencies. Sample values: 'USD' for US dollars, 'EUR' for euros, 'GBP' for British pounds"""
    merchant_id: str
    r"""Unique identifier for an organization"""
    name: str
    r"""Plan identifier visible to customers. Sample values: 'Basic Tier', 'Business Package', 'Enterprise Solution', 'Metered Billing', 'Free Tier', 'Premium Access'"""
    billing_interval: NotRequired[str]
    r"""Recurring billing period frequency. Sample values: 'monthly' for monthly billing, 'yearly' for annual billing, 'weekly' for weekly billing"""
    default_tax_code: NotRequired[str]
    r"""Default tax code for plan line items. Common values: 'eservice' (electronically supplied services), 'saas' (software as a service), 'consulting', 'ebook', 'standard', 'reduced', 'exempt'. Full list available via GET /tax/codes endpoint."""
    default_tax_rate: NotRequired[float]
    r"""Fallback tax rate percentage when automatic tax calculation fails. Sample values: 8.5 represents 8.5% tax, 10.0 represents 10% tax, 0 represents no tax"""
    description: NotRequired[str]
    r"""Plan details explaining included features and limits. Sample values: 'Claude API access with 500K tokens monthly allowance', 'Unlimited cloud storage plus real-time analytics tools', 'Complete machine learning infrastructure with GPU access', 'Flexible usage-based pricing with no monthly commitment'"""
    invoice_display_name: NotRequired[str]
    r"""Plan name shown on billing statements. Sample values: 'LLM API Basic Plan', 'Data Warehouse Business', 'ML Platform Enterprise', 'Pay-Per-Use Model'"""
    prices: NotRequired[List[str]]
    r"""Array of price IDs to associate with this plan"""
    product_id: NotRequired[str]
    r"""Unique identifier for a product"""
    tax_behavior: NotRequired[CreatePlanTaxBehavior]
    r"""Whether tax is added on top of the price (exclusive) or included in the price (inclusive)"""
    renewal_reminder_enabled: NotRequired[bool]
    r"""Whether to send renewal reminder emails to customers before their subscription renews"""
    renewal_reminder_days: NotRequired[int]
    r"""Number of days before renewal to send the reminder email"""
    billing_version: NotRequired[BillingVersion]
    r"""Billing engine version. 0 = legacy fee-schedule billing (Legacy), 1 = line-item billing with metered usage support (Standard)."""


class CreatePlanRequest(BaseModel):
    currency: str
    r"""Three-letter ISO 4217 currency code for plan pricing. Must be one of the merchant's supported currencies. Sample values: 'USD' for US dollars, 'EUR' for euros, 'GBP' for British pounds"""

    merchant_id: Annotated[str, pydantic.Field(alias="merchantId")]
    r"""Unique identifier for an organization"""

    name: str
    r"""Plan identifier visible to customers. Sample values: 'Basic Tier', 'Business Package', 'Enterprise Solution', 'Metered Billing', 'Free Tier', 'Premium Access'"""

    billing_interval: Annotated[
        Optional[str], pydantic.Field(alias="billingInterval")
    ] = None
    r"""Recurring billing period frequency. Sample values: 'monthly' for monthly billing, 'yearly' for annual billing, 'weekly' for weekly billing"""

    default_tax_code: Annotated[
        Optional[str], pydantic.Field(alias="defaultTaxCode")
    ] = "eservice"
    r"""Default tax code for plan line items. Common values: 'eservice' (electronically supplied services), 'saas' (software as a service), 'consulting', 'ebook', 'standard', 'reduced', 'exempt'. Full list available via GET /tax/codes endpoint."""

    default_tax_rate: Annotated[
        Optional[float], pydantic.Field(alias="defaultTaxRate")
    ] = 0
    r"""Fallback tax rate percentage when automatic tax calculation fails. Sample values: 8.5 represents 8.5% tax, 10.0 represents 10% tax, 0 represents no tax"""

    description: Optional[str] = None
    r"""Plan details explaining included features and limits. Sample values: 'Claude API access with 500K tokens monthly allowance', 'Unlimited cloud storage plus real-time analytics tools', 'Complete machine learning infrastructure with GPU access', 'Flexible usage-based pricing with no monthly commitment'"""

    invoice_display_name: Annotated[
        Optional[str], pydantic.Field(alias="invoiceDisplayName")
    ] = None
    r"""Plan name shown on billing statements. Sample values: 'LLM API Basic Plan', 'Data Warehouse Business', 'ML Platform Enterprise', 'Pay-Per-Use Model'"""

    prices: Optional[List[str]] = None
    r"""Array of price IDs to associate with this plan"""

    product_id: Annotated[Optional[str], pydantic.Field(alias="productId")] = None
    r"""Unique identifier for a product"""

    tax_behavior: Annotated[
        Optional[CreatePlanTaxBehavior], pydantic.Field(alias="taxBehavior")
    ] = "exclusive"
    r"""Whether tax is added on top of the price (exclusive) or included in the price (inclusive)"""

    renewal_reminder_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="renewalReminderEnabled")
    ] = True
    r"""Whether to send renewal reminder emails to customers before their subscription renews"""

    renewal_reminder_days: Annotated[
        Optional[int], pydantic.Field(alias="renewalReminderDays")
    ] = 3
    r"""Number of days before renewal to send the reminder email"""

    billing_version: Annotated[
        Optional[BillingVersion], pydantic.Field(alias="billingVersion")
    ] = 0
    r"""Billing engine version. 0 = legacy fee-schedule billing (Legacy), 1 = line-item billing with metered usage support (Standard)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "billingInterval",
                "defaultTaxCode",
                "defaultTaxRate",
                "description",
                "invoiceDisplayName",
                "prices",
                "productId",
                "taxBehavior",
                "renewalReminderEnabled",
                "renewalReminderDays",
                "billingVersion",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreatePlanRequest.model_rebuild()
except NameError:
    pass
