"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createmaximumquantityadjustment import (
    CreateMaximumQuantityAdjustment,
    CreateMaximumQuantityAdjustmentTypedDict,
)
from .createminimumquantityadjustment import (
    CreateMinimumQuantityAdjustment,
    CreateMinimumQuantityAdjustmentTypedDict,
)
from .createpercentagediscountadjustment import (
    CreatePercentageDiscountAdjustment,
    CreatePercentageDiscountAdjustmentTypedDict,
)
from .createusagediscountadjustment import (
    CreateUsageDiscountAdjustment,
    CreateUsageDiscountAdjustmentTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType


CreateSubscriptionAdjustmentRequestTypedDict = TypeAliasType(
    "CreateSubscriptionAdjustmentRequestTypedDict",
    Union[
        CreatePercentageDiscountAdjustmentTypedDict,
        CreateUsageDiscountAdjustmentTypedDict,
        CreateMinimumQuantityAdjustmentTypedDict,
        CreateMaximumQuantityAdjustmentTypedDict,
    ],
)
r"""One adjustment to attach to the subscription. The type decides which number the body carries: a rate for percentageDiscount, a unit count and one target price for usageDiscount, and a contracted quantity and one target price for minimumQuantity and maximumQuantity."""


CreateSubscriptionAdjustmentRequest = Annotated[
    Union[
        CreatePercentageDiscountAdjustment,
        CreateUsageDiscountAdjustment,
        CreateMinimumQuantityAdjustment,
        CreateMaximumQuantityAdjustment,
    ],
    Field(discriminator="type"),
]
r"""One adjustment to attach to the subscription. The type decides which number the body carries: a rate for percentageDiscount, a unit count and one target price for usageDiscount, and a contracted quantity and one target price for minimumQuantity and maximumQuantity."""
