"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitytype import EntityType
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateExternalReferenceRequestTypedDict(TypedDict):
    merchant_id: str
    entity_type: EntityType
    r"""The type of Paygentic entity this external reference points at"""
    entity_id: str
    r"""Paygentic id of the entity, e.g. `itm_xxx`"""
    provider: str
    r"""Lowercase snake_case provider identifier (e.g. `salesforce`, `netsuite`)"""
    external_id: str
    r"""Identifier of the record in the external system"""
    external_label: NotRequired[str]
    r"""Human-friendly name shown in UIs (e.g. a NetSuite financial-treatment name)"""
    metadata: NotRequired[Dict[str, Any]]
    r"""Provider-specific fields (e.g. `{ \"sfObject\": \"Product2\" }`)"""
    is_primary: NotRequired[bool]
    r"""Whether this is the canonical reference for `(provider, externalId)`. The primary is unique per merchant; non-primary references are aliases."""
    is_default: NotRequired[bool]
    r"""Whether this is the default target for the entity + provider. At most one default per `(entityType, entityId, provider)`."""


class CreateExternalReferenceRequest(BaseModel):
    merchant_id: Annotated[str, pydantic.Field(alias="merchantId")]

    entity_type: Annotated[EntityType, pydantic.Field(alias="entityType")]
    r"""The type of Paygentic entity this external reference points at"""

    entity_id: Annotated[str, pydantic.Field(alias="entityId")]
    r"""Paygentic id of the entity, e.g. `itm_xxx`"""

    provider: str
    r"""Lowercase snake_case provider identifier (e.g. `salesforce`, `netsuite`)"""

    external_id: Annotated[str, pydantic.Field(alias="externalId")]
    r"""Identifier of the record in the external system"""

    external_label: Annotated[Optional[str], pydantic.Field(alias="externalLabel")] = (
        None
    )
    r"""Human-friendly name shown in UIs (e.g. a NetSuite financial-treatment name)"""

    metadata: Optional[Dict[str, Any]] = None
    r"""Provider-specific fields (e.g. `{ \"sfObject\": \"Product2\" }`)"""

    is_primary: Annotated[Optional[bool], pydantic.Field(alias="isPrimary")] = True
    r"""Whether this is the canonical reference for `(provider, externalId)`. The primary is unique per merchant; non-primary references are aliases."""

    is_default: Annotated[Optional[bool], pydantic.Field(alias="isDefault")] = False
    r"""Whether this is the default target for the entity + provider. At most one default per `(entityType, entityId, provider)`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["externalLabel", "metadata", "isPrimary", "isDefault"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateExternalReferenceRequest.model_rebuild()
except NameError:
    pass
