"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
from paygentic_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeletePriceRequestTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the price"""


class DeletePriceRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the price"""


class DeletePriceItemTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    version_number: NotRequired[int]
    version_numbers: NotRequired[List[int]]


class DeletePriceItem(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    version_number: Annotated[Optional[int], pydantic.Field(alias="versionNumber")] = (
        None
    )

    version_numbers: Annotated[
        Optional[List[int]], pydantic.Field(alias="versionNumbers")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "versionNumber", "versionNumbers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeletePriceBlockerTypedDict(TypedDict):
    type: NotRequired[str]
    count: NotRequired[int]
    items: NotRequired[List[DeletePriceItemTypedDict]]


class DeletePriceBlocker(BaseModel):
    type: Optional[str] = None

    count: Optional[int] = None

    items: Optional[List[DeletePriceItem]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "count", "items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeletePriceDetailsTypedDict(TypedDict):
    blockers: NotRequired[List[DeletePriceBlockerTypedDict]]


class DeletePriceDetails(BaseModel):
    blockers: Optional[List[DeletePriceBlocker]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["blockers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DeletePriceItem.model_rebuild()
except NameError:
    pass
