"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscriptionintervaladdop import (
    SubscriptionIntervalAddOp,
    SubscriptionIntervalAddOpTypedDict,
)
from .subscriptionintervaleditop import (
    SubscriptionIntervalEditOp,
    SubscriptionIntervalEditOpTypedDict,
)
from .subscriptionintervalremoveop import (
    SubscriptionIntervalRemoveOp,
    SubscriptionIntervalRemoveOpTypedDict,
)
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class EditSubscriptionIntervalsRequestTypedDict(TypedDict):
    r"""An add/edit/remove op set to apply to the subscription's price timeline. At least one operation is required."""

    add: NotRequired[List[SubscriptionIntervalAddOpTypedDict]]
    r"""New override segments to add."""
    edit: NotRequired[List[SubscriptionIntervalEditOpTypedDict]]
    r"""Changes to existing intervals."""
    remove: NotRequired[List[SubscriptionIntervalRemoveOpTypedDict]]
    r"""Intervals to remove outright."""


class EditSubscriptionIntervalsRequest(BaseModel):
    r"""An add/edit/remove op set to apply to the subscription's price timeline. At least one operation is required."""

    add: Optional[List[SubscriptionIntervalAddOp]] = None
    r"""New override segments to add."""

    edit: Optional[List[SubscriptionIntervalEditOp]] = None
    r"""Changes to existing intervals."""

    remove: Optional[List[SubscriptionIntervalRemoveOp]] = None
    r"""Intervals to remove outright."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["add", "edit", "remove"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
