"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitytype import EntityType
from datetime import datetime
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ExternalReferenceObject = Literal["externalReference",]


class ExternalReferenceTypedDict(TypedDict):
    r"""Links a Paygentic entity to a record in an external system such as Salesforce or NetSuite."""

    id: str
    r"""Unique identifier for an external reference"""
    merchant_id: str
    r"""Unique identifier for an organization"""
    entity_type: EntityType
    r"""The type of Paygentic entity this external reference points at"""
    entity_id: str
    provider: str
    r"""Lowercase snake_case provider identifier (e.g. `salesforce`, `netsuite`)"""
    external_id: str
    r"""Optional external identifier for cross-referencing with external systems. Alphanumeric characters, hyphens, and underscores only."""
    metadata: Dict[str, Any]
    is_primary: bool
    is_default: bool
    created_at: datetime
    updated_at: datetime
    object: NotRequired[ExternalReferenceObject]
    external_label: NotRequired[Nullable[str]]


class ExternalReference(BaseModel):
    r"""Links a Paygentic entity to a record in an external system such as Salesforce or NetSuite."""

    id: str
    r"""Unique identifier for an external reference"""

    merchant_id: Annotated[str, pydantic.Field(alias="merchantId")]
    r"""Unique identifier for an organization"""

    entity_type: Annotated[EntityType, pydantic.Field(alias="entityType")]
    r"""The type of Paygentic entity this external reference points at"""

    entity_id: Annotated[str, pydantic.Field(alias="entityId")]

    provider: str
    r"""Lowercase snake_case provider identifier (e.g. `salesforce`, `netsuite`)"""

    external_id: Annotated[str, pydantic.Field(alias="externalId")]
    r"""Optional external identifier for cross-referencing with external systems. Alphanumeric characters, hyphens, and underscores only."""

    metadata: Dict[str, Any]

    is_primary: Annotated[bool, pydantic.Field(alias="isPrimary")]

    is_default: Annotated[bool, pydantic.Field(alias="isDefault")]

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]

    object: Optional[ExternalReferenceObject] = "externalReference"

    external_label: Annotated[
        OptionalNullable[str], pydantic.Field(alias="externalLabel")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object", "externalLabel"])
        nullable_fields = set(["externalLabel"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ExternalReference.model_rebuild()
except NameError:
    pass
