"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .item import Item, ItemTypedDict
from .offsetpagination import OffsetPagination, OffsetPaginationTypedDict
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
from paygentic_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListItemsRequestTypedDict(TypedDict):
    merchant_id: NotRequired[str]
    r"""Filter items by merchant organization id"""
    provider: NotRequired[str]
    r"""Provider whose external code to resolve (e.g. `salesforce`, `netsuite`). Must be supplied together with `externalId`."""
    external_id: NotRequired[str]
    r"""Resolve every live Item mapped to this `(provider, externalId)` — the canonical primary plus any non-primary aliases. The primary Item is returned first and is identifiable by its matching reference's `isPrimary: true`. Empty list on no match. Must be supplied together with `provider`."""
    limit: NotRequired[int]
    r"""Maximum items to return. In resolution mode (`provider`+`externalId` supplied) pagination is over the de-duplicated resolved Item set, primary Item first."""
    offset: NotRequired[int]
    r"""Zero-based offset for pagination. In resolution mode this paginates the de-duplicated resolved Item set."""


class ListItemsRequest(BaseModel):
    merchant_id: Annotated[
        Optional[str],
        pydantic.Field(alias="merchantId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter items by merchant organization id"""

    provider: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Provider whose external code to resolve (e.g. `salesforce`, `netsuite`). Must be supplied together with `externalId`."""

    external_id: Annotated[
        Optional[str],
        pydantic.Field(alias="externalId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Resolve every live Item mapped to this `(provider, externalId)` — the canonical primary plus any non-primary aliases. The primary Item is returned first and is identifiable by its matching reference's `isPrimary: true`. Empty list on no match. Must be supplied together with `provider`."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""Maximum items to return. In resolution mode (`provider`+`externalId` supplied) pagination is over the de-duplicated resolved Item set, primary Item first."""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Zero-based offset for pagination. In resolution mode this paginates the de-duplicated resolved Item set."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["merchantId", "provider", "externalId", "limit", "offset"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListItemsResponseTypedDict(TypedDict):
    r"""List of items"""

    data: List[ItemTypedDict]
    pagination: OffsetPaginationTypedDict
    r"""Offset-based pagination response."""


class ListItemsResponse(BaseModel):
    r"""List of items"""

    data: List[Item]

    pagination: OffsetPagination
    r"""Offset-based pagination response."""
