"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .offsetpagination import OffsetPagination, OffsetPaginationTypedDict
from .planversionsummary import PlanVersionSummary, PlanVersionSummaryTypedDict
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
from paygentic_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListPlanVersionsRequestTypedDict(TypedDict):
    id: str
    limit: NotRequired[int]
    r"""Maximum number of versions to return"""
    offset: NotRequired[int]
    r"""Number of versions to skip"""


class ListPlanVersionsRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10
    r"""Maximum number of versions to return"""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Number of versions to skip"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["limit", "offset"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ListPlanVersionsObject = Literal["list",]


class ListPlanVersionsResponseTypedDict(TypedDict):
    r"""List of plan versions"""

    object: ListPlanVersionsObject
    data: List[PlanVersionSummaryTypedDict]
    pagination: OffsetPaginationTypedDict
    r"""Offset-based pagination response."""


class ListPlanVersionsResponse(BaseModel):
    r"""List of plan versions"""

    object: ListPlanVersionsObject

    data: List[PlanVersionSummary]

    pagination: OffsetPagination
    r"""Offset-based pagination response."""
