"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


MerchantIntegrationProvider = Literal["salesforce",]
r"""External provider a merchant can connect at the tenant level"""
