"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


MeterEventObject = Literal["meterEvent",]


class MeterEventTypedDict(TypedDict):
    id: str
    r"""Unique event identifier"""
    type: str
    r"""CloudEvents event type (matches the meter's eventType)"""
    source: str
    r"""CloudEvents source that published the event"""
    subject: str
    r"""Subject of the event — typically the customer ID"""
    time: datetime
    r"""Time the event occurred"""
    idempotency_key: str
    r"""Caller-supplied idempotency key"""
    data: Dict[str, Any]
    r"""Event payload"""
    object: NotRequired[MeterEventObject]
    external_id: NotRequired[str]
    r"""Optional external identifier for cross-referencing with external systems. Alphanumeric characters, hyphens, and underscores only."""


class MeterEvent(BaseModel):
    id: str
    r"""Unique event identifier"""

    type: str
    r"""CloudEvents event type (matches the meter's eventType)"""

    source: str
    r"""CloudEvents source that published the event"""

    subject: str
    r"""Subject of the event — typically the customer ID"""

    time: datetime
    r"""Time the event occurred"""

    idempotency_key: Annotated[str, pydantic.Field(alias="idempotencyKey")]
    r"""Caller-supplied idempotency key"""

    data: Dict[str, Any]
    r"""Event payload"""

    object: Optional[MeterEventObject] = "meterEvent"

    external_id: Annotated[Optional[str], pydantic.Field(alias="externalId")] = None
    r"""Optional external identifier for cross-referencing with external systems. Alphanumeric characters, hyphens, and underscores only."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object", "externalId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    MeterEvent.model_rebuild()
except NameError:
    pass
