"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Literal, Union
from typing_extensions import Annotated, NotRequired, TypedDict


OrderBillingScheduleObject = Literal["billing_schedule",]


OrderBillingScheduleStatus = Union[
    Literal[
        "draft",
        "active",
        "completed",
        "cancelled",
    ],
    UnrecognizedStr,
]


OrderBillingScheduleAlignmentPolicy = Union[
    Literal[
        "anchor",
        "calendar",
        "coterm",
    ],
    UnrecognizedStr,
]


OrderBillingScheduleProrationPolicy = Union[
    Literal[
        "none",
        "daily",
    ],
    UnrecognizedStr,
]


OrderBillingSchedulePeriodPreset = Union[
    Literal[
        "single",
        "P1M",
        "P3M",
        "P6M",
        "P1Y",
        "custom",
    ],
    UnrecognizedStr,
]


class OrderBillingScheduleTypedDict(TypedDict):
    r"""Summary of a billing schedule owned by this order. The full schedule (with intervals + staged invoices) is served under /billingSchedules. Owner-polymorphic: a schedule belongs to exactly one Order or one Subscription (XOR); cadence lives on ScheduleIntervals, not the header."""

    id: str
    object: OrderBillingScheduleObject
    merchant_id: str
    status: OrderBillingScheduleStatus
    start_date: datetime
    end_date: datetime
    billing_anchor: datetime
    alignment_policy: OrderBillingScheduleAlignmentPolicy
    proration_policy: OrderBillingScheduleProrationPolicy
    period_preset: OrderBillingSchedulePeriodPreset
    metadata: Dict[str, Any]
    created_at: datetime
    updated_at: datetime
    order_id: NotRequired[Nullable[str]]
    subscription_id: NotRequired[Nullable[str]]
    payment_term_days: NotRequired[Nullable[int]]


class OrderBillingSchedule(BaseModel):
    r"""Summary of a billing schedule owned by this order. The full schedule (with intervals + staged invoices) is served under /billingSchedules. Owner-polymorphic: a schedule belongs to exactly one Order or one Subscription (XOR); cadence lives on ScheduleIntervals, not the header."""

    id: str

    object: OrderBillingScheduleObject

    merchant_id: Annotated[str, pydantic.Field(alias="merchantId")]

    status: OrderBillingScheduleStatus

    start_date: Annotated[datetime, pydantic.Field(alias="startDate")]

    end_date: Annotated[datetime, pydantic.Field(alias="endDate")]

    billing_anchor: Annotated[datetime, pydantic.Field(alias="billingAnchor")]

    alignment_policy: Annotated[
        OrderBillingScheduleAlignmentPolicy, pydantic.Field(alias="alignmentPolicy")
    ]

    proration_policy: Annotated[
        OrderBillingScheduleProrationPolicy, pydantic.Field(alias="prorationPolicy")
    ]

    period_preset: Annotated[
        OrderBillingSchedulePeriodPreset, pydantic.Field(alias="periodPreset")
    ]

    metadata: Dict[str, Any]

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]

    order_id: Annotated[OptionalNullable[str], pydantic.Field(alias="orderId")] = UNSET

    subscription_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="subscriptionId")
    ] = UNSET

    payment_term_days: Annotated[
        OptionalNullable[int], pydantic.Field(alias="paymentTermDays")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["orderId", "subscriptionId", "paymentTermDays"])
        nullable_fields = set(["orderId", "subscriptionId", "paymentTermDays"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    OrderBillingSchedule.model_rebuild()
except NameError:
    pass
