"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


PaymentMethodObject = Literal["paymentMethod",]


class PaymentMethodTypedDict(TypedDict):
    object: PaymentMethodObject
    id: str
    r"""Payment method identifier."""
    created_at: datetime
    type: NotRequired[Nullable[str]]
    r"""Payment method type (e.g. `card`, `sepa_debit`)."""
    brand: NotRequired[Nullable[str]]
    last4: NotRequired[Nullable[str]]
    exp_month: NotRequired[Nullable[int]]
    exp_year: NotRequired[Nullable[int]]


class PaymentMethod(BaseModel):
    object: PaymentMethodObject

    id: str
    r"""Payment method identifier."""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    type: OptionalNullable[str] = UNSET
    r"""Payment method type (e.g. `card`, `sepa_debit`)."""

    brand: OptionalNullable[str] = UNSET

    last4: OptionalNullable[str] = UNSET

    exp_month: Annotated[OptionalNullable[int], pydantic.Field(alias="expMonth")] = (
        UNSET
    )

    exp_year: Annotated[OptionalNullable[int], pydantic.Field(alias="expYear")] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "brand", "last4", "expMonth", "expYear"])
        nullable_fields = set(["type", "brand", "last4", "expMonth", "expYear"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    PaymentMethod.model_rebuild()
except NameError:
    pass
