"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .planlineinput import PlanLineInput, PlanLineInputTypedDict
from typing import Union
from typing_extensions import TypeAliasType


PlanLineRefTypedDict = TypeAliasType(
    "PlanLineRefTypedDict", Union[PlanLineInputTypedDict, str]
)
r"""Either a price ID on its own, or a price ID with the key that names its line."""


PlanLineRef = TypeAliasType("PlanLineRef", Union[PlanLineInput, str])
r"""Either a price ID on its own, or a price ID with the key that names its line."""
