"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


class PercentagePricePropertiesTypedDict(TypedDict):
    r"""Percentage pricing model"""

    max_charge: str
    r"""Ceiling amount limiting total charge regardless of percentage calculation. Sample values: '500.00' caps fees at $500 maximum, '2000.00' limits charges to $2000 per period"""
    min_charge: str
    r"""Floor amount charged regardless of percentage calculation. Sample values: '5.00' ensures minimum $5 fee, '25.00' guarantees at least $25 per billing event"""
    percentage: str
    r"""Rate expressed as decimal between 0 and 10, supporting up to 4 decimal precision. Sample values: '0.03' represents 3%, '0.075' represents 7.5%, '1.10' represents 110%"""


class PercentagePriceProperties(BaseModel):
    r"""Percentage pricing model"""

    max_charge: Annotated[str, pydantic.Field(alias="maxCharge")]
    r"""Ceiling amount limiting total charge regardless of percentage calculation. Sample values: '500.00' caps fees at $500 maximum, '2000.00' limits charges to $2000 per period"""

    min_charge: Annotated[str, pydantic.Field(alias="minCharge")]
    r"""Floor amount charged regardless of percentage calculation. Sample values: '5.00' ensures minimum $5 fee, '25.00' guarantees at least $25 per billing event"""

    percentage: str
    r"""Rate expressed as decimal between 0 and 10, supporting up to 4 decimal precision. Sample values: '0.03' represents 3%, '0.075' represents 7.5%, '1.10' represents 110%"""


class VolumeTierTypedDict(TypedDict):
    up_to: Nullable[str]
    r"""Inclusive upper bound of the band, as a decimal string. Null on the last band only, which carries the remainder. Sample values: '100' bounds the band at 100 units, null leaves the top open."""
    unit_price: str
    r"""Per-unit cost inside this band, as a decimal string, capped at 6 decimal places. Sample values: '5' represents $5 per unit, '0.004' represents $0.004 per unit."""


class VolumeTier(BaseModel):
    up_to: Annotated[Nullable[str], pydantic.Field(alias="upTo")]
    r"""Inclusive upper bound of the band, as a decimal string. Null on the last band only, which carries the remainder. Sample values: '100' bounds the band at 100 units, null leaves the top open."""

    unit_price: Annotated[str, pydantic.Field(alias="unitPrice")]
    r"""Per-unit cost inside this band, as a decimal string, capped at 6 decimal places. Sample values: '5' represents $5 per unit, '0.004' represents $0.004 per unit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class VolumePricePropertiesTypedDict(TypedDict):
    r"""Volume pricing model"""

    tiers: List[VolumeTierTypedDict]
    r"""Ordered ladder of bands. The band is selected by the period's total metered usage, and its rate applies to every billed unit. A band matches when the quantity is less than or equal to its `upTo`, and the first matching band wins; the previous band's `upTo` is the exclusive lower bound, and the first band's floor is 0."""


class VolumePriceProperties(BaseModel):
    r"""Volume pricing model"""

    tiers: List[VolumeTier]
    r"""Ordered ladder of bands. The band is selected by the period's total metered usage, and its rate applies to every billed unit. A band matches when the quantity is less than or equal to its `upTo`, and the first matching band wins; the previous band's `upTo` is the exclusive lower bound, and the first band's floor is 0."""


class DynamicPricePropertiesTypedDict(TypedDict):
    r"""Dynamic pricing model"""

    max_price: str
    r"""Upper limit of the price range for dynamic pricing. Sample values: '0.10' means $0.10 per token for large volumes at peak times"""
    min_price: str
    r"""Lower limit of the price range for dynamic pricing. Sample values: '0.01' means $0.01 per token for low volumes during off-peak hours"""


class DynamicPriceProperties(BaseModel):
    r"""Dynamic pricing model"""

    max_price: Annotated[str, pydantic.Field(alias="maxPrice")]
    r"""Upper limit of the price range for dynamic pricing. Sample values: '0.10' means $0.10 per token for large volumes at peak times"""

    min_price: Annotated[str, pydantic.Field(alias="minPrice")]
    r"""Lower limit of the price range for dynamic pricing. Sample values: '0.01' means $0.01 per token for low volumes during off-peak hours"""


class StandardPricePropertiesTypedDict(TypedDict):
    r"""Standard pricing model"""

    unit_price: str
    r"""Per-unit cost in decimal format for fixed-rate pricing. Sample values: '0.00002' represents $0.00002 per token, '0.15' represents $0.15 per gigabyte stored, '0.05' represents $0.05 per API call. Per unit. Total per period = quantity × unitPrice; see the `quantity` field. A negative value defines a usage-scaled rebate: the line's subtotal is negative and reduces the invoice. A rebate never drives an invoice total below zero, so set rebate rates below the charges they offset. A negative unitPrice is only valid on a metered price (a billableMetricId is required — there is no usage to scale on a fee price) and cannot be combined with grantDiscountEnabled, a hard-limit feature, or a pricingUnitId. When a rebate and a charge price share a billable metric but attach to different features, they compute against different quantity bases: a price attached to a feature bills the overage against its allowance, while a featureless price bills the raw metered usage. That is a permitted configuration, not an error. Attach both to the same feature to bill them against one basis."""


class StandardPriceProperties(BaseModel):
    r"""Standard pricing model"""

    unit_price: Annotated[str, pydantic.Field(alias="unitPrice")]
    r"""Per-unit cost in decimal format for fixed-rate pricing. Sample values: '0.00002' represents $0.00002 per token, '0.15' represents $0.15 per gigabyte stored, '0.05' represents $0.05 per API call. Per unit. Total per period = quantity × unitPrice; see the `quantity` field. A negative value defines a usage-scaled rebate: the line's subtotal is negative and reduces the invoice. A rebate never drives an invoice total below zero, so set rebate rates below the charges they offset. A negative unitPrice is only valid on a metered price (a billableMetricId is required — there is no usage to scale on a fee price) and cannot be combined with grantDiscountEnabled, a hard-limit feature, or a pricingUnitId. When a rebate and a charge price share a billable metric but attach to different features, they compute against different quantity bases: a price attached to a feature bills the overage against its allowance, while a featureless price bills the raw metered usage. That is a permitted configuration, not an error. Attach both to the same feature to bill them against one basis."""


PricePropertiesTypedDict = TypeAliasType(
    "PricePropertiesTypedDict",
    Union[
        StandardPricePropertiesTypedDict,
        VolumePricePropertiesTypedDict,
        DynamicPricePropertiesTypedDict,
        PercentagePricePropertiesTypedDict,
    ],
)


PriceProperties = TypeAliasType(
    "PriceProperties",
    Union[
        StandardPriceProperties,
        VolumePriceProperties,
        DynamicPriceProperties,
        PercentagePriceProperties,
    ],
)


try:
    PercentagePriceProperties.model_rebuild()
except NameError:
    pass
try:
    VolumeTier.model_rebuild()
except NameError:
    pass
try:
    DynamicPriceProperties.model_rebuild()
except NameError:
    pass
try:
    StandardPriceProperties.model_rebuild()
except NameError:
    pass
