"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, TypedDict


class ProfitabilityTrendTypedDict(TypedDict):
    values: List[str]
    r"""Revenue values per time bucket, oldest first, in unit currency with two decimals."""
    period_change: Nullable[float]
    r"""Period-over-period % change (current half vs prior half). Null when prior is zero."""


class ProfitabilityTrend(BaseModel):
    values: List[str]
    r"""Revenue values per time bucket, oldest first, in unit currency with two decimals."""

    period_change: Annotated[Nullable[float], pydantic.Field(alias="periodChange")]
    r"""Period-over-period % change (current half vs prior half). Null when prior is zero."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    ProfitabilityTrend.model_rebuild()
except NameError:
    pass
