"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class ProfitabilityRowTypedDict(TypedDict):
    customer_id: str
    r"""Customer ID, or the literal 'other' for the overflow row."""
    customer_name: str
    r"""Display name for the row. 'Other' for the overflow row."""
    net_revenue: str
    r"""Revenue excluding tax (paid + outstanding invoices issued in the period), in unit currency, with two decimals."""
    total_cost: str
    r"""Aggregated cost in unit currency, with two decimals."""
    profit: str
    r"""Profit (revenue − cost) in unit currency, with two decimals. May be negative."""
    margin_pct: Nullable[str]
    r"""Margin percent (profit / revenue × 100), with two decimals. Null when revenue is zero."""


class ProfitabilityRow(BaseModel):
    customer_id: Annotated[str, pydantic.Field(alias="customerId")]
    r"""Customer ID, or the literal 'other' for the overflow row."""

    customer_name: Annotated[str, pydantic.Field(alias="customerName")]
    r"""Display name for the row. 'Other' for the overflow row."""

    net_revenue: Annotated[str, pydantic.Field(alias="netRevenue")]
    r"""Revenue excluding tax (paid + outstanding invoices issued in the period), in unit currency, with two decimals."""

    total_cost: Annotated[str, pydantic.Field(alias="totalCost")]
    r"""Aggregated cost in unit currency, with two decimals."""

    profit: str
    r"""Profit (revenue − cost) in unit currency, with two decimals. May be negative."""

    margin_pct: Annotated[Nullable[str], pydantic.Field(alias="marginPct")]
    r"""Margin percent (profit / revenue × 100), with two decimals. Null when revenue is zero."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    ProfitabilityRow.model_rebuild()
except NameError:
    pass
