"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .purchasegrantrequest import PurchaseGrantRequest, PurchaseGrantRequestTypedDict
from paygentic_sdk.types import BaseModel
from paygentic_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class PurchaseEntitlementGrantRequestTypedDict(TypedDict):
    entitlement_id: str
    r"""The unique identifier of the entitlement to purchase credits for."""
    purchase_grant_request: PurchaseGrantRequestTypedDict


class PurchaseEntitlementGrantRequest(BaseModel):
    entitlement_id: Annotated[
        str,
        pydantic.Field(alias="entitlementId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier of the entitlement to purchase credits for."""

    purchase_grant_request: Annotated[
        PurchaseGrantRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
