"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pricefeature import PriceFeature, PriceFeatureTypedDict
from .pricemodel import PriceModel
from .priceproperties import PriceProperties, PricePropertiesTypedDict
from datetime import datetime
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


SchemasPriceObject = Literal["price",]


SchemasPricePaymentTerm = Union[
    Literal[
        "in_arrears",
        "in_advance",
    ],
    UnrecognizedStr,
]


class SchemasPriceTypedDict(TypedDict):
    id: str
    r"""Unique identifier for a price"""
    merchant_id: str
    r"""Unique identifier for an organization"""
    created_at: datetime
    invoice_display_name: str
    payment_term: SchemasPricePaymentTerm
    properties: PricePropertiesTypedDict
    updated_at: datetime
    quantity: int
    r"""Quantity for invoice line items. Total per period = quantity × unitPrice. Only supported for fee prices; metered prices derive quantity from usage. Defaults to 1."""
    object: NotRequired[SchemasPriceObject]
    billable_metric_id: NotRequired[str]
    r"""Unique identifier for a billable metric"""
    fee_id: NotRequired[str]
    r"""The unique identifier for the fee referred to by this price. Present when price is linked to a fee."""
    pricing_unit_id: NotRequired[str]
    r"""Unique identifier for a pricing unit"""
    billing_cadence: NotRequired[Nullable[str]]
    r"""ISO 8601 duration. 'P0D' for one-time, 'P1M' for monthly, 'P1Y' for yearly. Required for fees, optional for billable metrics. Defaults to plan's billingCadence if not specified."""
    model: NotRequired[PriceModel]
    r"""Pricing model of a price as returned by the API. Includes the legacy models ('dynamic', 'percentage') retained for existing prices; 'standard' and 'volume' can be created (see PriceModelInput)."""
    features: NotRequired[List[PriceFeatureTypedDict]]
    r"""Features associated with this price"""
    grant_discount_enabled: NotRequired[bool]
    r"""When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices."""
    is_obligation: NotRequired[bool]
    r"""A fixed amount owed whole rather than a per-period rate. An obligation is not prorated over a partial first period: when a subscription starts before its billing anchor, no truncated stub is billed and the first charge is the full amount at the next anchor. An obligation also refuses an interval boundary that falls strictly inside one of its own billing periods, since part of an amount owed whole is not a thing to bill. Defaults to false, which is a rate and is today's behaviour for every price. Not supported on a metered price, whose amount resolves from usage at close."""


class SchemasPrice(BaseModel):
    id: str
    r"""Unique identifier for a price"""

    merchant_id: Annotated[str, pydantic.Field(alias="merchantId")]
    r"""Unique identifier for an organization"""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    invoice_display_name: Annotated[str, pydantic.Field(alias="invoiceDisplayName")]

    payment_term: Annotated[
        SchemasPricePaymentTerm, pydantic.Field(alias="paymentTerm")
    ]

    properties: PriceProperties

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]

    quantity: int
    r"""Quantity for invoice line items. Total per period = quantity × unitPrice. Only supported for fee prices; metered prices derive quantity from usage. Defaults to 1."""

    object: Optional[SchemasPriceObject] = "price"

    billable_metric_id: Annotated[
        Optional[str], pydantic.Field(alias="billableMetricId")
    ] = None
    r"""Unique identifier for a billable metric"""

    fee_id: Annotated[Optional[str], pydantic.Field(alias="feeId")] = None
    r"""The unique identifier for the fee referred to by this price. Present when price is linked to a fee."""

    pricing_unit_id: Annotated[Optional[str], pydantic.Field(alias="pricingUnitId")] = (
        None
    )
    r"""Unique identifier for a pricing unit"""

    billing_cadence: Annotated[
        OptionalNullable[str], pydantic.Field(alias="billingCadence")
    ] = UNSET
    r"""ISO 8601 duration. 'P0D' for one-time, 'P1M' for monthly, 'P1Y' for yearly. Required for fees, optional for billable metrics. Defaults to plan's billingCadence if not specified."""

    model: Optional[PriceModel] = None
    r"""Pricing model of a price as returned by the API. Includes the legacy models ('dynamic', 'percentage') retained for existing prices; 'standard' and 'volume' can be created (see PriceModelInput)."""

    features: Optional[List[PriceFeature]] = None
    r"""Features associated with this price"""

    grant_discount_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="grantDiscountEnabled")
    ] = False
    r"""When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices."""

    is_obligation: Annotated[Optional[bool], pydantic.Field(alias="isObligation")] = (
        False
    )
    r"""A fixed amount owed whole rather than a per-period rate. An obligation is not prorated over a partial first period: when a subscription starts before its billing anchor, no truncated stub is billed and the first charge is the full amount at the next anchor. An obligation also refuses an interval boundary that falls strictly inside one of its own billing periods, since part of an amount owed whole is not a thing to bill. Defaults to false, which is a rate and is today's behaviour for every price. Not supported on a metered price, whose amount resolves from usage at close."""

    @model_serializer(mode="wrap")
    def _serialize_model(self, handler):
        optional_fields = set(
            [
                "object",
                "billableMetricId",
                "feeId",
                "pricingUnitId",
                "billingCadence",
                "model",
                "features",
                "grantDiscountEnabled",
                "isObligation",
            ]
        )
        nullable_fields = set(["billingCadence"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    SchemasPrice.model_rebuild()
except NameError:
    pass
