"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import BaseModel
from typing_extensions import TypedDict


class SubscriptionIntervalRemoveOpTypedDict(TypedDict):
    id: str
    r"""The interval being removed."""


class SubscriptionIntervalRemoveOp(BaseModel):
    id: str
    r"""The interval being removed."""
