"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .changereason import ChangeReason
from .intervalchangemetadata import (
    IntervalChangeMetadata,
    IntervalChangeMetadataTypedDict,
)
from .subscriptionintervalchangeentry import (
    SubscriptionIntervalChangeEntry,
    SubscriptionIntervalChangeEntryTypedDict,
)
from datetime import datetime
from paygentic_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class SubscriptionIntervalChangeTypedDict(TypedDict):
    r"""The record of one change to a subscription's price intervals: what changed, and why."""

    id: str
    merchant_id: str
    subscription_id: str
    change_reason: ChangeReason
    r"""Why a change was made. `correction` fixes data to match what was agreed; `migration` moves a contract from another system; `commercial` is a real change to the deal. Defaults to `unspecified`."""
    description: Nullable[str]
    metadata: Dict[str, IntervalChangeMetadataTypedDict]
    r"""Your own key-value data about the change, such as a CRM deal ID."""
    created_at: datetime
    intervals: List[SubscriptionIntervalChangeEntryTypedDict]
    r"""One entry per interval the edit added, changed or removed."""


class SubscriptionIntervalChange(BaseModel):
    r"""The record of one change to a subscription's price intervals: what changed, and why."""

    id: str

    merchant_id: Annotated[str, pydantic.Field(alias="merchantId")]

    subscription_id: Annotated[str, pydantic.Field(alias="subscriptionId")]

    change_reason: Annotated[ChangeReason, pydantic.Field(alias="changeReason")]
    r"""Why a change was made. `correction` fixes data to match what was agreed; `migration` moves a contract from another system; `commercial` is a real change to the deal. Defaults to `unspecified`."""

    description: Nullable[str]

    metadata: Dict[str, IntervalChangeMetadata]
    r"""Your own key-value data about the change, such as a CRM deal ID."""

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    intervals: List[SubscriptionIntervalChangeEntry]
    r"""One entry per interval the edit added, changed or removed."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    SubscriptionIntervalChange.model_rebuild()
except NameError:
    pass
