"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .offsetpagination import OffsetPagination, OffsetPaginationTypedDict
from .subscriptionintervalchange import (
    SubscriptionIntervalChange,
    SubscriptionIntervalChangeTypedDict,
)
from paygentic_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SubscriptionIntervalChangesResponseTypedDict(TypedDict):
    data: List[SubscriptionIntervalChangeTypedDict]
    pagination: OffsetPaginationTypedDict
    r"""Offset-based pagination response."""


class SubscriptionIntervalChangesResponse(BaseModel):
    data: List[SubscriptionIntervalChange]

    pagination: OffsetPagination
    r"""Offset-based pagination response."""
