"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import UnrecognizedStr
from typing import Literal, Union


SubscriptionVersionPolicy = Union[
    Literal[
        "floating",
        "pinned",
    ],
    UnrecognizedStr,
]
r"""How the subscription follows new versions of its plan. `floating` follows the plan's default version: when the default changes, the subscription bills from the new default from its next billing period. `pinned` keeps the plan version that the subscription holds. A subscription created without a value is `floating`. A change to this value does not change a billing period that has already started."""
