"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscriptionintervalchangecopy import (
    SubscriptionIntervalChangeCopy,
    SubscriptionIntervalChangeCopyTypedDict,
)
from paygentic_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class SubscriptionIntervalChangeEntryTypedDict(TypedDict):
    r"""One interval that the change added, edited or removed, with its state before and after."""

    interval_id: str
    before: Nullable[SubscriptionIntervalChangeCopyTypedDict]
    r"""The interval before the edit. Null when the edit added it."""
    after: Nullable[SubscriptionIntervalChangeCopyTypedDict]
    r"""The interval after the edit. Null when the edit removed it."""


class SubscriptionIntervalChangeEntry(BaseModel):
    r"""One interval that the change added, edited or removed, with its state before and after."""

    interval_id: Annotated[str, pydantic.Field(alias="intervalId")]

    before: Nullable[SubscriptionIntervalChangeCopy]
    r"""The interval before the edit. Null when the edit added it."""

    after: Nullable[SubscriptionIntervalChangeCopy]
    r"""The interval after the edit. Null when the edit removed it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    SubscriptionIntervalChangeEntry.model_rebuild()
except NameError:
    pass
