"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from paygentic_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from paygentic_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


UpdateSubscriptionStatus = Literal[
    "active",
    "terminated",
]


class UpdateSubscriptionRequestBodyTypedDict(TypedDict):
    ending_at: NotRequired[datetime]
    status: NotRequired[UpdateSubscriptionStatus]
    terminated_at: NotRequired[datetime]
    terminated_by: NotRequired[str]
    r"""Identifier of entity that cancelled the subscription. Sample values: 'cust_abc123' for customer-initiated cancellation, 'org_xyz789' for merchant-initiated cancellation"""
    termination_reason: NotRequired[str]
    r"""Explanation for subscription cancellation. Sample values: 'Customer requested cancellation', 'Payment failure', 'Service migration', 'Contract expiration'"""
    auto_charge: NotRequired[bool]
    r"""Enable or disable automatic charging of invoices using stored payment methods."""
    tax_exempt: NotRequired[bool]
    r"""When true, forces tax rate to 0%."""
    minimum_account_balance: NotRequired[str]
    r"""Minimum wallet balance requirement in decimal dollars (e.g., '100.00'). Can be set to '0' to disable. Maximum allowed is $5,000. Contact support for higher limits. Note: If the calculated charge amount at renewal is below payment processor minimums (typically $1.00), it will be automatically adjusted upward to meet the minimum requirement. Changes apply at next renewal."""
    renewal_reminder_enabled: NotRequired[Nullable[bool]]
    r"""Override plan setting for renewal reminder emails. Set to true to enable, false to disable, or null to use plan default."""
    renewal_reminder_days: NotRequired[Nullable[int]]
    r"""Override plan setting for number of days before renewal to send the reminder. Set to null to use plan default."""


class UpdateSubscriptionRequestBody(BaseModel):
    ending_at: Annotated[Optional[datetime], pydantic.Field(alias="endingAt")] = None

    status: Optional[UpdateSubscriptionStatus] = None

    terminated_at: Annotated[
        Optional[datetime], pydantic.Field(alias="terminatedAt")
    ] = None

    terminated_by: Annotated[Optional[str], pydantic.Field(alias="terminatedBy")] = None
    r"""Identifier of entity that cancelled the subscription. Sample values: 'cust_abc123' for customer-initiated cancellation, 'org_xyz789' for merchant-initiated cancellation"""

    termination_reason: Annotated[
        Optional[str], pydantic.Field(alias="terminationReason")
    ] = None
    r"""Explanation for subscription cancellation. Sample values: 'Customer requested cancellation', 'Payment failure', 'Service migration', 'Contract expiration'"""

    auto_charge: Annotated[Optional[bool], pydantic.Field(alias="autoCharge")] = None
    r"""Enable or disable automatic charging of invoices using stored payment methods."""

    tax_exempt: Annotated[Optional[bool], pydantic.Field(alias="taxExempt")] = None
    r"""When true, forces tax rate to 0%."""

    minimum_account_balance: Annotated[
        Optional[str], pydantic.Field(alias="minimumAccountBalance")
    ] = None
    r"""Minimum wallet balance requirement in decimal dollars (e.g., '100.00'). Can be set to '0' to disable. Maximum allowed is $5,000. Contact support for higher limits. Note: If the calculated charge amount at renewal is below payment processor minimums (typically $1.00), it will be automatically adjusted upward to meet the minimum requirement. Changes apply at next renewal."""

    renewal_reminder_enabled: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="renewalReminderEnabled")
    ] = UNSET
    r"""Override plan setting for renewal reminder emails. Set to true to enable, false to disable, or null to use plan default."""

    renewal_reminder_days: Annotated[
        OptionalNullable[int], pydantic.Field(alias="renewalReminderDays")
    ] = UNSET
    r"""Override plan setting for number of days before renewal to send the reminder. Set to null to use plan default."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "endingAt",
                "status",
                "terminatedAt",
                "terminatedBy",
                "terminationReason",
                "autoCharge",
                "taxExempt",
                "minimumAccountBalance",
                "renewalReminderEnabled",
                "renewalReminderDays",
            ]
        )
        nullable_fields = set(["renewalReminderEnabled", "renewalReminderDays"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateSubscriptionRequestTypedDict(TypedDict):
    id: str
    request_body: UpdateSubscriptionRequestBodyTypedDict


class UpdateSubscriptionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        UpdateSubscriptionRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


try:
    UpdateSubscriptionRequestBody.model_rebuild()
except NameError:
    pass
