"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from paygentic_sdk.types import BaseModel, UNSET_SENTINEL
from paygentic_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class VoidInvoiceRefundRequestBodyTypedDict(TypedDict):
    reason: NotRequired[str]
    r"""Optional reason for voiding the refund (recorded on the credit note)"""


class VoidInvoiceRefundRequestBody(BaseModel):
    reason: Optional[str] = None
    r"""Optional reason for voiding the refund (recorded on the credit note)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reason"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VoidInvoiceRefundRequestTypedDict(TypedDict):
    id: str
    r"""The invoice ID"""
    refund_id: str
    r"""The refund (credit note) ID"""
    request_body: NotRequired[VoidInvoiceRefundRequestBodyTypedDict]


class VoidInvoiceRefundRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The invoice ID"""

    refund_id: Annotated[
        str,
        pydantic.Field(alias="refundId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The refund (credit note) ID"""

    request_body: Annotated[
        Optional[VoidInvoiceRefundRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
