"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from paygentic_sdk.errors import PaygenticError
from paygentic_sdk.models import updatepriceop as models_updatepriceop
from paygentic_sdk.types import BaseModel
from typing import Optional


class UpdatePriceConflictErrorData(BaseModel):
    message: str
    code: str
    r"""Machine-readable conflict code. Open set: a new code may appear, so branch on the ones you handle and treat anything else as an unhandled conflict."""
    error: Optional[str] = None
    details: Optional[models_updatepriceop.UpdatePriceDetails] = None


@dataclass(unsafe_hash=True)
class UpdatePriceConflictError(PaygenticError):
    r"""Price cannot be restructured because a subscription still bills it directly"""

    data: UpdatePriceConflictErrorData = field(hash=False)

    def __init__(
        self,
        data: UpdatePriceConflictErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
